LOAD FROM \"NYPD_Motor_Vehicle_Collisions2017.csv\" 
OF  DEL MODIFIED BY dateformat=\"MM\/DD\/YYYY\" TIMEFORMAT=\"H:MM\" METHOD P ( 1, 2, 4, 5, 6, 19, 20, 24, 25, 26 ) 
MESSAGES \"messages.txt\" 
INSERT INTO CSE532.COLLISION ( DATE, TIME, ZIP_CODE, LATITUDE, LONGITUDE, 
CONTRIBUTING_FACTOR_VEHICLE1, CONTRIBUTING_FACTOR_VEHICLE2, UNIQUE_KEY, 
VEHICLE_TYPE_CODE_1, VEHICLE_TYPE_CODE_2)
